### ISSUE TITLE
Reporting handled errors

### ISSUE THREAD

**Issue by kw-pr** [shopware-blog/shopware-bugsnag#1]
I would like to report handled errors from my article import plugin:

https://docs.bugsnag.com/platforms/php/other/#reporting-handled-exceptions

Any idea how I would get the `$bugsnag` object from your plugin?

**Comment by kw-pr** [comment]
Well, this would work, but globales are bad. So, I never said this:

    $GLOBALS['Bugsnag'] = $bugSnag;

**Comment by teiling88** [comment]
Hey kw-pr, 
with this commit https://github.com/shopware-blog/shopware-bugsnag/commit/9305c0bec1bb19c1a69611ff6f9af93c76fb0d86 I uses the new api. Now you can receive the bugsnagClient with die DI-Key "shopware_blog_bugsnag.source.bugsnag_client"

**Comment by kw-pr** [comment]
Hey teiling,
thanks, that does work. Very nice!
I see you also updated to the new Bugsnag lib, cool.
Maybe you should add something about `composer install` in the readme.

**Comment by teiling88** [comment]
> Maybe you should add something about composer install in the readme.

Yes, I thought about it but I think if you see a composer.json file the `composer install` command is obvious or?

**Comment by kw-pr** [comment]
Yes, even more obvious is the composer.lock :)

I figured it out because of the /vendor in gitignore...

So yes, it is obvious but it would no hurt. And we all had that morning without coffee where we just can not see the obvious :D
