### ISSUE TITLE
Feature Request: hide user ip

### ISSUE THREAD

**Issue by kw-pr** [shopware-blog/shopware-bugsnag#2]
By default bugsnag logs user IP addresses. This is a legal issue in Europe.
It would be nice to have a config option for this:

        // Replaces the automatically collected IP
        $bugSnag->setBeforeNotifyFunction(function ($error) {
            $error->setMetaData([
                'request' => [
                    'clientIp' => null
                ]
            ]);
            $error->setUser([
                'id' => null,
            ]);
        });

Source: https://github.com/bugsnag/bugsnag-php/issues/480#issuecomment-394298611

**Comment by teiling88** [comment]
Fixed with: https://github.com/shopware-blog/shopware-bugsnag/commit/ee3f36e329a5bb9b2f98caee876ba2ee751371c8
