### ISSUE TITLE
Shopware Commands Errors are not captured

### ISSUE THREAD

**Issue by kw-pr** [shopware-blog/shopware-bugsnag#3]
I noticed errors from Shopware command line are not captured.

Looks like the plugin is not loaded at all in this case. I tried to find a better hook but no luck so far.

Also a problem could be the error handler in `Shopware/Commands/ShopwareCommand.php::registerErrorHandler()`...

**Comment by teiling88** [comment]
Fixed with: https://github.com/shopware-blog/shopware-bugsnag/commit/ee3f36e329a5bb9b2f98caee876ba2ee751371c8
